// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjLhg2XYqzVrAtPl07p4Y_Y_DAJsm02JE',
    appId: '1:977984385567:web:12812d46ee745abc589b2a',
    messagingSenderId: '977984385567',
    projectId: 'saudievents-99e16',
    authDomain: 'saudievents-99e16.firebaseapp.com',
    storageBucket: 'saudievents-99e16.appspot.com',
    measurementId: 'G-S2X39Y3EDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrd9f4ZpwRlX-TII0TJ7H1XThYQfVnElA',
    appId: '1:977984385567:android:612344d3aa222fb9589b2a',
    messagingSenderId: '977984385567',
    projectId: 'saudievents-99e16',
    storageBucket: 'saudievents-99e16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXbmjhL0RgivoEVpHCDyvf1wucujtvxXs',
    appId: '1:977984385567:ios:d0e62e8c242997f3589b2a',
    messagingSenderId: '977984385567',
    projectId: 'saudievents-99e16',
    storageBucket: 'saudievents-99e16.appspot.com',
    iosBundleId: 'com.example.sudiaEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXbmjhL0RgivoEVpHCDyvf1wucujtvxXs',
    appId: '1:977984385567:ios:3b00721b454c6512589b2a',
    messagingSenderId: '977984385567',
    projectId: 'saudievents-99e16',
    storageBucket: 'saudievents-99e16.appspot.com',
    iosBundleId: 'com.example.sudiaEvents.RunnerTests',
  );
}
